name: Deploy to Website

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Run after our weekly meeting
  schedule:
  - cron: "13 23 * * 4"

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Needed for sitemap generation with valid lastmod https://github.com/facebook/docusaurus/pull/9954#issuecomment-2032900942
          fetch-depth: 0
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
      - name: Deploy to Server
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
